<# .SYNOPSIS Offline regression for layered, policy-first enterprise evidence admission. #>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$root=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;$tmp=Join-Path $root '.qianlima\tmp\enterprise-data-admission';New-Item -ItemType Directory -Path $tmp -Force|Out-Null;$runner=Join-Path $PSScriptRoot 'invoke-enterprise-data-admission.ps1';$now=(Get-Date).ToUniversalTime();$hash='a'*64
function W($n,$v){$p=Join-Path $tmp $n;[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));$p}
$grant=[ordered]@{grant_id='g1';task_id='t1';agent_id='external-research';organization_id='org1';department_id='dept1';project_id='project1';device_id='device1';data_refs=@('source:strong','source:weak','source:third','source:other-org','source:revoked','source:confidential');budget=[ordered]@{max_evidence_items=2};expires_at=$now.AddMinutes(10).ToString('o');status='issued'}
$request=[ordered]@{request_id='r1';task_id='t1';agent_id='external-research';grant_id='g1';organization_id='org1';department_id='dept1';project_id='project1';device_id='device1';device_attestation='verified';purpose='sanitized research';risk_level='L3';target='external_agent';max_items=2;allowed_classifications=@('public','internal_sanitized','confidential_reference_only');now=$now.ToString('o')}
function C($id,$source,$class,$org,$state,$revoked,$relevance,$quality,$cost,$risk){[ordered]@{evidence_id=$id;source_type='document';source_ref=$source;version='v1';classification=$class;organization_id=$org;department_id='dept1';project_id='project1';state=$state;valid_from=$now.AddDays(-1).ToString('o');valid_to=$now.AddDays(1).ToString('o');retention_until=$now.AddDays(30).ToString('o');revoked_at=$revoked;verification_status='verified';content_sha256=$hash;sanitized_excerpt="sanitized-$id";relevance_score=$relevance;evidence_quality=$quality;freshness_score=.8;retrieval_cost=$cost;exposure_risk=$risk}}
$candidates=[ordered]@{candidates=@((C strong source:strong internal_sanitized org1 current $null .8 .95 .1 .1),(C weak source:weak public org1 current $null .95 .4 .1 .1),(C third source:third public org1 current $null .5 .5 .2 .2),(C other source:other-org public org2 current $null 1 1 0 0),(C revoked source:revoked public org1 current $now.ToString('o') 1 1 0 0),(C confidential source:confidential confidential_reference_only org1 current $null 1 1 0 0))}
$rp=W request.json $request;$gp=W grant.json $grant;$cp=W candidates.json $candidates;$result=&$runner -RequestPath $rp -GrantPath $gp -CandidatePath $cp -PassThru|ConvertFrom-Json
$bad=$request.PSObject.Copy();$bad.device_id='other-device';$bp=W bad-request.json $bad;$badOut=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $runner -RequestPath $bp -GrantPath $gp -CandidatePath $cp -PassThru 2>&1;$badCode=$LASTEXITCODE
$cases=@(
  [pscustomobject]@{name='mandatory_filter_runs_before_ranking';passed=($result.policy_filter_applied_before_ranking-and-not$result.learned_end_to_end_selector_used-and$result.eligible_count-eq3-and$result.denied_count-eq3)},
  [pscustomobject]@{name='four_layers_are_explicit';passed=(@($result.layers.PSObject.Properties.Name).Count-eq4-and$result.layers.L0_policy_context.visibility-eq'broker_and_audit_only')},
  [pscustomobject]@{name='external_dispatch_is_L2_sanitized_only';passed=($result.dispatch_payload.layer-eq'L2_candidate_evidence'-and@($result.dispatch_payload.items).Count-eq2-and-not$result.dispatch_payload.knowledge_search_capability)},
  [pscustomobject]@{name='L3_contains_refs_not_original_content';passed=(@($result.layers.L3_original_references.items).Count-eq2-and-not$result.layers.L3_original_references.original_content_included-and@($result.layers.L3_original_references.items|?{$_.jit_read_requirement-ne'new_task_bound_grant_and_policy_recheck'}).Count-eq0)},
  [pscustomobject]@{name='quality_can_beat_higher_relevance';passed=($result.evidence_pack[0].evidence_id-eq'strong')},
  [pscustomobject]@{name='explicit_cost_and_exposure_penalties_recorded';passed=($null-ne$result.evidence_pack[0].score_components.retrieval_cost_penalty-and$null-ne$result.evidence_pack[0].score_components.exposure_risk_penalty)},
  [pscustomobject]@{name='top_k_exclusion_is_audited';passed=(@($result.not_selected_candidates).Count-eq1-and$result.not_selected_candidates[0].reason-eq'below_top_k')},
  [pscustomobject]@{name='policy_denials_are_audited';passed=(@($result.denied_candidates|?{$_.evidence_id-in@('other','revoked','confidential')}).Count-eq3)},
  [pscustomobject]@{name='external_agent_never_gets_search_raw_or_original';passed=(-not$result.search_capability_granted-and-not$result.raw_paths_returned-and-not$result.raw_private_content_returned-and-not$result.original_content_returned)},
  [pscustomobject]@{name='device_mismatch_denied_at_L0';passed=($badCode-ne0-and($badOut-join"`n")-match'L0_policy_context')}
)
$failed=@($cases|?{-not$_.passed});$r=[pscustomobject]@{passed=($failed.Count-eq0);cases=$cases;external_calls=$false;permissions_granted=$false};if($PassThru){$r|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise data admission regression failed: '+(($failed.name)-join', '))}
