param([switch]$PassThru)
$ErrorActionPreference='Stop'
$root=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path
$tmp=Join-Path $root ('tmp\collaboration-scale-' + [Guid]::NewGuid().ToString('n'));New-Item -ItemType Directory -Path $tmp -Force|Out-Null
$gate=Join-Path $PSScriptRoot 'invoke-enterprise-collaboration-scale-gate.ps1'
$now=[DateTimeOffset]::UtcNow
function P($n,$role,$employee){[ordered]@{employee_id=$employee;agent_id="agent-$n";agent_version='v1';role=$role;work_order_id="work-$n";grant_id="grant-$n";grant_status='issued';grant_expires_at=$now.AddMinutes(10).ToString('o');grant_task_id='task-1';grant_employee_id=$employee;grant_agent_id="agent-$n";grant_department_id='dept-1';allowed_tools=@('read_evidence');can_delegate=$false;evidence_pack_ref="evidence-pack:$n";data_classification='internal_sanitized';budget=[ordered]@{cost_usd=1;tool_calls=2}}}
function Approval($id,$employee,$role){[ordered]@{approval_id=$id;approver_employee_id=$employee;approver_role=$role;organization_id='org-1';department_id='dept-1';project_id='project-1';task_id='task-1';decision='approved';valid_from=$now.AddMinutes(-1).ToString('o');expires_at=$now.AddMinutes(10).ToString('o')}}
function BaseRequest { [ordered]@{collaboration_id='collab-scale';tenant_id='tenant-1';organization_id='org-1';department_id='dept-1';project_id='project-1';task_id='task-1';risk_level='L3';coordinator_employee_id='manager-1';manager_approval=(Approval 'approval-manager' 'manager-2' 'department_manager');participants=@((P 1 candidate employee-1),(P 2 independent_verifier employee-2));direct_agent_to_agent='deny';requested_budget=[ordered]@{cost_usd=3;tool_calls=5};direct_mcp_session_refs=@('mcp-session:1');status='requested'} }
function BaseState { [ordered]@{department_active_agents=2;organization_active_agents=4;department_pending_verifications=1;manager_pending_approvals=2;department_remaining_budget_usd=100;audit_available=$true} }
function Run($name,$request,$state){$rp=Join-Path $tmp "$name-request.json";$sp=Join-Path $tmp "$name-state.json";[IO.File]::WriteAllText($rp,($request|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($sp,($state|ConvertTo-Json -Depth 6),[Text.UTF8Encoding]::new($false));$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate -RequestPath $rp -StatePath $sp -PassThru 2>&1;[pscustomobject]@{code=$LASTEXITCODE;result=(($out-join"`n")|ConvertFrom-Json)}}
$cases=[System.Collections.Generic.List[object]]::new();function C($n,$p){$cases.Add([pscustomobject]@{name=$n;passed=[bool]$p})}
$a=Run admitted (BaseRequest) (BaseState);C 'eligible_collaboration_admitted_without_authority' ($a.code -eq 0 -and $a.result.decision -eq 'admitted' -and -not $a.result.grants_issued -and -not $a.result.execution_authorized)
$r=BaseRequest;$r.participants[1].grant_id='grant-1';$b=Run shared_grant $r (BaseState);C 'shared_grant_rejected' ($b.code-eq2-and$b.result.violations-contains'shared_grant_denied')
$r=BaseRequest;$r.manager_approval=$null;$c=Run no_approval $r (BaseState);C 'L3_without_manager_approval_rejected' ($c.code-eq2-and$c.result.violations-contains'manager_approval_required')
$r=BaseRequest;$r.manager_approval.department_id='other-dept';$scope=Run approval_scope $r (BaseState);C 'approval_scope_mismatch_rejected' ($scope.code-eq2-and$scope.result.violations-contains'manager_approval_scope_mismatch')
$r=BaseRequest;$r.direct_agent_to_agent='allow';$d=Run direct $r (BaseState);C 'direct_agent_connection_rejected' ($d.code-eq2)
$r=BaseRequest;$r.participants[0].grant_agent_id='other-agent';$binding=Run bad_binding $r (BaseState);C 'grant_binding_mismatch_rejected' ($binding.code-eq2-and$binding.result.violations-contains'grant_agent_binding_mismatch')
$s=BaseState;$s.department_pending_verifications=20;$e=Run backpressure (BaseRequest) $s;C 'verification_backpressure_pauses_without_expansion' ($e.code-eq3-and$e.result.decision-eq'paused'-and-not$e.result.grants_issued)
$r=BaseRequest;$r.risk_level='L4';$r.candidate_only=$true;$r.human_approval=Approval 'approval-human' 'owner-1' 'business_owner';$f=Run l4 $r (BaseState);C 'L4_distinct_human_candidate_only_admitted' ($f.code-eq0)
$r=BaseRequest;$r.risk_level='L4';$r.candidate_only=$false;$r.human_approval=Approval 'approval-human' 'employee-1' 'business_owner';$g=Run l4_bad $r (BaseState);C 'L4_self_approval_or_execution_rejected' ($g.code-eq2-and$g.result.violations-contains'approver_must_be_distinct'-and$g.result.violations-contains'L4_candidate_only_required')
$r=BaseRequest;$r.batch_approval=[ordered]@{batch_approval_id='batch-1';approver_id='manager-1';profile='data_external';organization_id='org-1';department_id='dept-1';project_id='project-1';valid_from=$now.AddMinutes(-1).ToString('o');expires_at=$now.AddMinutes(5).ToString('o');aggregate_limit=10;units_used=0};$h=Run batch_external $r (BaseState);C 'external_data_batch_approval_rejected' ($h.code-eq2-and$h.result.violations-contains'batch_approval_profile_denied')
C 'revocation_manifest_covers_entire_team' (@($a.result.revocation_manifest.participant_grant_ids).Count-eq2-and@($a.result.revocation_manifest.required_on)-contains'employee_offboarded')
$failed=@($cases|Where-Object{-not$_.passed});$result=[pscustomobject]@{passed=($failed.Count-eq0);cases=@($cases);external_calls=$false;permissions_granted=$false};if($PassThru){$result|ConvertTo-Json -Depth 7}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise collaboration scale regression failed: '+($failed.name-join', '))}
