<##
.SYNOPSIS
  Enqueues one idempotent reference-only memory indexing job without blocking interaction.
##>
param([Parameter(Mandatory=$true)][string]$MemoryPath,[Parameter(Mandatory=$true)][string]$IdempotencyKey,[Parameter(Mandatory=$true)][string]$RequestedBy,[string]$OutputPath='',[switch]$PassThru)
$ErrorActionPreference='Stop';$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$recordRoot=[IO.Path]::GetFullPath((Join-Path $projectRoot '.qianlima/run-traces/enterprise-memory/records')).TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar;$queueRoot=[IO.Path]::GetFullPath((Join-Path $projectRoot '.qianlima/run-traces/enterprise-memory/ingest-queue')).TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar
function Emit([hashtable]$Value,[int]$Code=0){if($PassThru){$Value|ConvertTo-Json -Depth 10}else{$Value|Format-List};if($Code-ne0){exit $Code}}
try{$full=(Resolve-Path -LiteralPath $MemoryPath -ErrorAction Stop).Path;$record=Get-Content -LiteralPath $full -Raw -Encoding UTF8|ConvertFrom-Json}catch{Emit ([ordered]@{status='blocked';reason='memory_record_not_found_or_invalid';queued=$false}) 1};if(-not$full.StartsWith($recordRoot,[StringComparison]::OrdinalIgnoreCase)){Emit ([ordered]@{status='blocked';reason='memory_record_outside_governed_root';queued=$false}) 1};if([string]$record.status-ne'candidate'){Emit ([ordered]@{status='blocked';reason='async_ingest_accepts_candidate_record_only';queued=$false}) 1};if([string]::IsNullOrWhiteSpace($IdempotencyKey)){Emit ([ordered]@{status='blocked';reason='idempotency_key_required';queued=$false}) 1}
$fingerprintInput=([string]$record.memory_id+'|'+[string]$record.content_ref+'|'+[string]$record.record_version+'|'+$IdempotencyKey);$sha=[Security.Cryptography.SHA256]::Create();try{$fingerprint=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($fingerprintInput)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath=Join-Path $queueRoot "$fingerprint.json"};$outputFull=[IO.Path]::GetFullPath($OutputPath);if(-not$outputFull.StartsWith($queueRoot,[StringComparison]::OrdinalIgnoreCase)){Emit ([ordered]@{status='blocked';reason='ingest_job_outside_governed_queue';queued=$false}) 1};if(Test-Path -LiteralPath $outputFull){Emit ([ordered]@{status='already_queued';job_fingerprint=$fingerprint;queued=$true;duplicate_suppressed=$true;process_started=$false;external_calls=$false})}
$job=[ordered]@{schema_version=1;job_id='memory-ingest-'+[Guid]::NewGuid().ToString('n');job_fingerprint=$fingerprint;memory_id=[string]$record.memory_id;cube_id=[string]$record.cube_id;memory_layer=[string]$record.memory_layer;tenant_id=[string]$record.tenant_id;organization_id=[string]$record.organization_id;project_id=[string]$record.project_id;role_id=[string]$record.role_id;classification=[string]$record.classification;content_ref=[string]$record.content_ref;source_refs=@($record.source_refs);record_version=[string]$record.record_version;owner_id=[string]$record.owner_id;audit_chain_ref=[string]$record.audit_chain_ref;requested_by=$RequestedBy;status='queued';security_checked_before_enqueue=$true;raw_payload_in_queue=$false;max_attempts=3;dead_letter_on_failure=$true;created_at=[DateTime]::UtcNow.ToString('o')};New-Item -ItemType Directory -Path (Split-Path -Parent $outputFull) -Force|Out-Null;[IO.File]::WriteAllText($outputFull,($job|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));Emit ([ordered]@{status='queued';job_id=$job.job_id;job_fingerprint=$fingerprint;job_path=$outputFull;queued=$true;interaction_blocked=$false;process_started=$false;external_calls=$false;business_write=$false})
