param([switch]$PassThru)
$ErrorActionPreference='Stop';$root=$PSScriptRoot;$architecture=Get-Content -LiteralPath (Join-Path $root 'northstar-control-plane-architecture.json') -Raw -Encoding UTF8|ConvertFrom-Json;$execution=Get-Content -LiteralPath (Join-Path $root 'execution-package-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json;$alignment=Get-Content -LiteralPath (Join-Path $root 'cross-functional-alignment-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json
$cases = @(
  [pscustomobject]@{name='four_planes_have_distinct_ownership';passed=((@($architecture.planes.psobject.Properties.Name).Count -eq 4) -and (@($architecture.planes.control.owns) -contains 'Grant') -and (@($architecture.planes.work.owns) -contains 'Plan') -and ($architecture.planes.execution.entry_object -eq 'ExecutionPackage'))},
  [pscustomobject]@{name='execution_has_single_controlled_entry';passed=(($architecture.single_execution_entry.model_direct_execution -eq 'deny') -and ($architecture.single_execution_entry.business_module_direct_connector_execution -eq 'deny') -and (@($architecture.planes.execution.requires) -contains 'trajectory_gate'))},
  [pscustomobject]@{name='event_envelope_is_append_only_and_reference_bound';passed=(($architecture.event_envelope.source_of_truth -match 'append_only') -and (@($architecture.event_envelope.required_when_execution_package_bound) -contains 'execution_package_id') -and (@($architecture.event_envelope.prohibited) -contains 'secret_value'))},
  [pscustomobject]@{name='existing_contracts_preserve_no_authority_bypass';passed=(($execution.model_authority -eq 'proposal_only') -and ($alignment.field_ownership.all_external_or_business_writes -eq 'Enterprise_L4_separate_grant_approval_readback'))}
)
$failed=@($cases|Where-Object{-not$_.passed});$out=[pscustomobject]@{passed=($failed.Count-eq0);cases=$cases;external_calls=$false;business_write=$false};if($PassThru){$out|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Control plane architecture regression failed: '+(($failed.name)-join', '))}
