<##
.SYNOPSIS
  Offline regression for local secret boundaries and API field-level least privilege.
##>
param([switch]$PassThru)
$ErrorActionPreference = 'Stop'
$gate = Join-Path $PSScriptRoot 'invoke-enterprise-api-access-gate.ps1'
$cases = [System.Collections.Generic.List[object]]::new()
function Run-Gate([string[]]$Arguments) { $old=$ErrorActionPreference; $ErrorActionPreference='Continue'; $out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1); $code=$LASTEXITCODE; $ErrorActionPreference=$old; $value=$null; try { $value=($out -join "`n") | ConvertFrom-Json } catch {}; [PSCustomObject]@{ code=$code; value=$value } }
function Add-Case([string]$Name,[bool]$Passed) { $cases.Add([PSCustomObject]@{ name=$Name; passed=$Passed }) }
function Set-Arg([string[]]$Arguments,[string]$Name,[string]$Value) { $out=[System.Collections.Generic.List[string]]::new(); for($i=0;$i -lt $Arguments.Count;$i++){ if($Arguments[$i] -eq $Name){$i++;continue};[void]$out.Add($Arguments[$i]) };[void]$out.Add($Name);[void]$out.Add($Value);return ,$out.ToArray() }
$base=@('-ProviderProfile','example_readonly','-Operation','read_selected','-DataClassification','internal_sanitized','-TaskId','task-1','-GrantId','grant-1','-ProviderId','provider-1','-CredentialRef','secretref:env/EXAMPLE_API_TOKEN','-Purpose','Read selected metrics for the approved task','-TimeRange','2026-07-01/2026-07-07','-DataScope','project-1','-Budget','0.50','-RequestedFields','entity_id,marketplace,date_from,date_to,metric_names')
$allowed=Run-Gate $base; Add-Case 'allowlisted_read_returns_broker_plan' ($allowed.code -eq 0 -and $allowed.value.status -eq 'broker_plan_allowed' -and -not $allowed.value.provider_called)
$whole=Run-Gate (Set-Arg $base '-RequestedFields' 'entity_id,password'); Add-Case 'secret_field_denied' ($whole.code -ne 0 -and @($whole.value.reasons) -contains 'request_field_not_allowlisted_password')
$raw=Run-Gate (Set-Arg $base '-CredentialRef' 'sk-live-secret-value'); Add-Case 'raw_credential_value_denied' ($raw.code -ne 0 -and (@($raw.value.reasons) -contains 'credential_must_be_local_secret_reference' -or @($raw.value.reasons) -contains 'credential_value_not_accepted'))
$unknown=Run-Gate (Set-Arg $base '-RequestedFields' 'entity_id,unbounded_query'); Add-Case 'unlisted_request_field_denied' ($unknown.code -ne 0 -and @($unknown.value.reasons) -contains 'request_field_not_allowlisted_unbounded_query')
$writeBase=@('-ProviderProfile','example_controlled_write','-Operation','execute_write','-DataClassification','internal_sanitized','-TaskId','task-write','-GrantId','grant-write','-ProviderId','provider-write','-CredentialRef','secretref:os/EXAMPLE_WRITE_TOKEN','-Purpose','Apply one approved change','-TimeRange','2026-07-23','-DataScope','project-1','-Budget','1.00','-RequestedFields','entity_id,change_reason,effective_at,idempotency_key','-BodyFields','entity_id,change_reason,effective_at,new_value,idempotency_key','-IndependentVerifier','-SanitizedEvidence','-SecretScanPassed','-PersonalDataScanPassed','-ScopeScanPassed','-FieldAllowlistScanPassed','-ActiveGrant','-ApprovedOperator','-SecondConfirmation','-PreflightSnapshot','-IdempotencyKey','-RollbackRef')
$write=Run-Gate $writeBase; Add-Case 'allowlisted_l4_write_is_plan_only' ($write.code -eq 0 -and $write.value.status -eq 'broker_plan_ready_after_confirmation' -and -not $write.value.provider_called -and -not $write.value.permissions_granted)
$writeDenied=Run-Gate ($writeBase | Where-Object { $_ -notin @('-SecondConfirmation') }); Add-Case 'l4_missing_second_confirmation_denied' ($writeDenied.code -ne 0 -and @($writeDenied.value.reasons) -contains 'second_confirmation_required_for_L4')
$body=Run-Gate (Set-Arg $writeBase '-BodyFields' 'entity_id,bulk_selector'); Add-Case 'unlisted_body_field_denied' ($body.code -ne 0 -and @($body.value.reasons) -contains 'body_field_not_allowlisted_bulk_selector')
$cross=Run-Gate (Set-Arg $base '-DataClassification' 'confidential_reference_only'); Add-Case 'confidential_cross_validation_requires_sanitized_evidence' ($cross.code -ne 0 -and @($cross.value.reasons) -contains 'independent_sanitized_verification_required')
$crossOk=Set-Arg $base '-DataClassification' 'confidential_reference_only'; $crossOk=Run-Gate ($crossOk + @('-IndependentVerifier','-SanitizedEvidence','-SecretScanPassed','-PersonalDataScanPassed','-ScopeScanPassed','-FieldAllowlistScanPassed')); Add-Case 'cross_validation_receives_no_raw_payload' ($crossOk.code -eq 0 -and $crossOk.value.raw_payload_to_model -eq $false -and $crossOk.value.agent_receives -eq 'sanitized_projected_result_only')
$failed=@($cases | Where-Object { -not $_.passed }); $result=[PSCustomObject]@{ passed=($failed.Count -eq 0); cases=@($cases); provider_calls=$false; network_opened=$false; credential_values_exposed=$false; permissions_granted=$false }; if ($PassThru) { $result | ConvertTo-Json -Depth 8 } else { $cases | Format-Table -AutoSize }; if ($failed.Count -gt 0) { throw "Enterprise API access regression failed: $($failed.name -join ', ')" }
