param([switch]$PassThru)
$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$tmp=Join-Path ([IO.Path]::GetTempPath()) 'beijixing-enterprise-task-terminal-test';New-Item -ItemType Directory -Path $tmp -Force|Out-Null;$stamp=(Get-Date).ToString('yyyyMMddHHmmssfff')
$issuer=Join-Path $PSScriptRoot 'new-enterprise-ad-diagnostic-v1-grant.ps1';$closer=Join-Path $PSScriptRoot 'complete-enterprise-task.ps1';$grantId="grant-terminal-$stamp";$taskId="task-terminal-$stamp";$traceId="trace-terminal-$stamp";$grantPath=Join-Path $projectRoot ".qianlima\run-traces\delegation-grants\$grantId.json"
$issue=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $issuer -GrantId $grantId -TaskId $taskId -TenantId tenant-1 -OrganizationId org-1 -EmployeeId employee-1 -DeviceId device-1 -ProjectId project-1 -CostCenter ads-1 -AgentId ad-readonly-agent -AgentVersion ad-diagnostic-v1 -TraceId $traceId -AttestationStatus verified -OutputPath $grantPath -PassThru);if($LASTEXITCODE-ne 0){throw 'Terminal test Grant issuance failed.'}
$pending=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $closer -GrantPath $grantPath -ActorId platform-admin-1 -TerminalStatus completed -VerificationStatus pending -PassThru 2>&1);$pendingCode=$LASTEXITCODE
$close=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $closer -GrantPath $grantPath -ActorId platform-admin-1 -TerminalStatus completed -VerificationStatus passed -EvidenceReceiptRef receipt:terminal-$stamp -Reason task_completed -PassThru);$closeCode=$LASTEXITCODE;$closeResult=(($close|ForEach-Object{$_.ToString()})-join "`n")|ConvertFrom-Json
$repeat=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $closer -GrantPath $grantPath -ActorId platform-admin-1 -TerminalStatus cancelled -Reason duplicate_attempt -PassThru 2>&1);$repeatCode=$LASTEXITCODE
$auditPath=Join-Path $projectRoot '.qianlima\run-traces\enterprise-audit-events.jsonl';$events=@(Get-Content -LiteralPath $auditPath -Encoding UTF8|ForEach-Object{try{$_|ConvertFrom-Json}catch{}}|Where-Object{$_.task_id-eq$taskId});$revoked=@($events|Where-Object{$_.event_type-eq'grant_revoked'});$terminal=@($events|Where-Object{$_.event_type-eq'task_terminal'});$revokedIndex=[array]::IndexOf($events,$revoked[0]);$terminalIndex=[array]::IndexOf($events,$terminal[0])
$cases=@([pscustomobject]@{name='completion_requires_verified_receipt';passed=($pendingCode-ne 0-and(($pending|ForEach-Object{$_.ToString()})-join"`n")-match'verified_receipt_required_for_completion')},[pscustomobject]@{name='completion_revokes_and_closes_task';passed=($closeCode-eq 0-and$closeResult.status-eq'completed'-and$closeResult.grant_revoked-eq$true-and$closeResult.execution_authorized-eq$false)},[pscustomobject]@{name='grant_revoked_before_terminal_event';passed=(@($revoked).Count-eq 1-and@($terminal).Count-eq 1-and$revokedIndex-ge 0-and$terminalIndex-gt$revokedIndex)},[pscustomobject]@{name='terminal_task_cannot_reopen';passed=($repeatCode-ne 0-and(($repeat|ForEach-Object{$_.ToString()})-join"`n")-match'task_already_terminal')},[pscustomobject]@{name='terminal_has_no_external_execution';passed=($closeResult.external_calls-eq$false-and$closeResult.process_started-eq$false)})
$failed=@($cases|Where-Object{-not$_.passed});$out=[pscustomobject]@{passed=($failed.Count-eq 0);cases=$cases;external_calls=$false;process_started=$false;business_write=$false};if($PassThru){$out|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise task terminal regression failed: '+(($failed.name)-join ', '))}
