param([switch]$PassThru)
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$stamp = (Get-Date).ToString('yyyyMMddHHmmssfff')
$taskId = "bundle-replenishment-task-$stamp"; $grantId = "bundle-replenishment-grant-$stamp"; $traceId = "bundle-replenishment-trace-$stamp"
$tmp = Join-Path ([IO.Path]::GetTempPath()) "beijixing-bundle-replenishment-$stamp"; New-Item -ItemType Directory -Path $tmp -Force | Out-Null
$grantPath = Join-Path $root ".qianlima\run-traces\delegation-grants\$grantId.json"; $draftPath = Join-Path $root ".qianlima\run-traces\enterprise-procurement-drafts\draft-$stamp.json"; $inputPath = Join-Path $tmp 'fixture.json'
$grant = [ordered]@{schema_version=1; contract_type='beijixing_enterprise_task_grant'; grant_id=$grantId; status='issued'; task_id=$taskId; tenant_id='tenant-supply'; organization_id='org-supply'; employee_id='operator-supply'; device_id='device-supply'; project_id='project-supply'; cost_center='supply'; agent_id='bundle-replenishment-agent'; agent_version='v1'; trace_id=$traceId; data_scope=@('inventory_procurement'); allowed_operations=@('read_bom','read_inventory','read_supplier_directory'); allowed_tools=@('bundle_replenishment_v1'); expires_at=[DateTime]::UtcNow.AddMinutes(10).ToString('o'); network_access='none'; write_access='none'; can_delegate=$false}
New-Item -ItemType Directory -Path (Split-Path -Parent $grantPath) -Force | Out-Null; [IO.File]::WriteAllText($grantPath, ($grant | ConvertTo-Json -Depth 10), [Text.UTF8Encoding]::new($false))
$fixture = [ordered]@{
  plan = [ordered]@{plan_id='bundle-plan-a'; bundle_sku='BUNDLE-A'; planned_quantity=100; required_available_date='2026-08-20'; owner_id='operations-owner'; task_id=$taskId; tenant_id='tenant-supply'; organization_id='org-supply'; project_id='project-supply'; source_refs=@('bom://BUNDLE-A/v1','inventory://snapshot/2026-08-01','inbound://snapshot/2026-08-01','supplier://directory/v1')}
  bom = @([ordered]@{bundle_sku='BUNDLE-A';component_sku='X';quantity_per_bundle=1;bom_version='v1'},[ordered]@{bundle_sku='BUNDLE-A';component_sku='Y';quantity_per_bundle=1;bom_version='v1'},[ordered]@{bundle_sku='BUNDLE-A';component_sku='Z';quantity_per_bundle=1;bom_version='v1'})
  inventory = @([ordered]@{component_sku='X';physical_quantity=50;order_locked_quantity=10;bundle_reserved_quantity=5;quality_hold_quantity=0},[ordered]@{component_sku='Y';physical_quantity=140;order_locked_quantity=10;bundle_reserved_quantity=10;quality_hold_quantity=0},[ordered]@{component_sku='Z';physical_quantity=70;order_locked_quantity=5;bundle_reserved_quantity=5;quality_hold_quantity=0})
  inbound = @([ordered]@{component_sku='X';purchase_order_ref='po://x-confirmed';unallocated_quantity=40;eta='2026-08-15';status='supplier_confirmed'},[ordered]@{component_sku='Z';purchase_order_ref='po://z-late';unallocated_quantity=100;eta='2026-08-25';status='shipped'},[ordered]@{component_sku='Z';purchase_order_ref='po://z-unconfirmed';unallocated_quantity=100;eta='2026-08-10';status='submitted_unconfirmed'})
  suppliers = @([ordered]@{component_sku='X';supplier_id='supplier-x';status='active';is_preferred=$true;priority=1;supplier_profile_ref='supplier://x';product_link_ref='product://x';contact_ref='contact://x';wechat_ref='wechat://x';moq=50;case_pack=10;last_purchase_price=12.5;lead_time_days=12},[ordered]@{component_sku='Z';supplier_id='supplier-z';status='active';is_preferred=$true;priority=1;supplier_profile_ref='supplier://z';product_link_ref='product://z';contact_ref='contact://z';wechat_ref='wechat://z';moq=50;case_pack=10;last_purchase_price=8.0;lead_time_days=10})
}
[IO.File]::WriteAllText($inputPath, ($fixture | ConvertTo-Json -Depth 12), [Text.UTF8Encoding]::new($false))
$planner = Join-Path $PSScriptRoot 'new-bundle-replenishment-draft.ps1'; $raw = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $planner -InputPath $inputPath -GrantPath $grantPath -OutputPath $draftPath -PassThru 2>&1); $code = $LASTEXITCODE; $result = (($raw | ForEach-Object { $_.ToString() }) -join "`n") | ConvertFrom-Json
$draft = if (Test-Path -LiteralPath $draftPath) { Get-Content -LiteralPath $draftPath -Raw -Encoding UTF8 | ConvertFrom-Json } else { $null }; $x = @($draft.items | Where-Object component_sku -eq 'X')[0]; $y = @($draft.items | Where-Object component_sku -eq 'Y')[0]; $z = @($draft.items | Where-Object component_sku -eq 'Z')[0]
$duplicate = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $planner -InputPath $inputPath -GrantPath $grantPath -OutputPath $draftPath -PassThru 2>&1); $duplicateCode = $LASTEXITCODE
$cases = @(
  [pscustomobject]@{name='draft_is_readonly_and_nonexecuting';passed=($code -eq 0 -and $draft.status -eq 'purchase_requisition_draft' -and $draft.purchase_order_created -eq $false -and $draft.execution_authorized -eq $false -and $draft.erp_write_performed -eq $false)},
  [pscustomobject]@{name='available_inventory_excludes_locked_reserved_and_hold';passed=($x.available_inventory -eq 35 -and $y.available_inventory -eq 120 -and $z.available_inventory -eq 60)},
  [pscustomobject]@{name='confirmed_on_time_inbound_reduces_shortage';passed=($x.confirmed_on_time_inbound -eq 40 -and $x.shortage -eq 25 -and $x.suggested_order_quantity -eq 50)},
  [pscustomobject]@{name='sufficient_component_has_no_purchase';passed=($y.shortage -eq 0 -and $y.suggested_order_quantity -eq 0 -and $null -eq $y.supplier)},
  [pscustomobject]@{name='late_and_unconfirmed_inbound_do_not_reduce_shortage';passed=($z.confirmed_on_time_inbound -eq 0 -and $z.shortage -eq 40 -and $z.suggested_order_quantity -eq 50 -and @($z.late_inbound_risk).Count -eq 1)},
  [pscustomobject]@{name='supplier_details_are_references_not_contact_action';passed=($x.supplier.wechat_ref -eq 'wechat://x' -and $draft.supplier_contacted -eq $false)},
  [pscustomobject]@{name='draft_cannot_be_overwritten';passed=($duplicateCode -ne 0 -and (($duplicate | ForEach-Object { $_.ToString() }) -join "`n") -match 'draft_already_exists')}
)
$failed = @($cases | Where-Object { -not $_.passed }); $out = [pscustomobject]@{passed=($failed.Count -eq 0);cases=$cases;external_calls=$false;business_write=$false;execution_authorized=$false}; if ($PassThru) { $out | ConvertTo-Json -Depth 8 } else { $cases | Format-Table -AutoSize }; if ($failed.Count) { throw ('Bundle replenishment regression failed: ' + (($failed.name) -join ', ')) }
