<##
.SYNOPSIS
  Offline regression for immutable, Grant-bound enterprise memory.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;. (Join-Path $PSScriptRoot 'resolve-enterprise-powershell.ps1');$runtime=Get-EnterprisePowerShellCommand
$stamp=(Get-Date).ToString('yyyyMMddHHmmssfff');$memoryId="enterprise-memory-$stamp";$taskId="memory-task-$stamp";$grantId="memory-grant-$stamp";$traceId="memory-trace-$stamp"
$recordPath=Join-Path $projectRoot ".qianlima/run-traces/enterprise-memory/records/$memoryId.json";$grantPath=Join-Path $projectRoot ".qianlima/run-traces/delegation-grants/$grantId.json";$sharePath=Join-Path $projectRoot ".qianlima/run-traces/enterprise-memory/share-grants/share-$stamp.json"
function Invoke-Child([string]$Script,[string[]]$Arguments){$raw=@(& $runtime -NoProfile -File $Script @Arguments 2>&1);[pscustomobject]@{code=$LASTEXITCODE;text=(($raw|ForEach-Object{$_.ToString()})-join"`n")}}
function Add-Case($Cases,[string]$Name,[bool]$Passed){$Cases.Add([pscustomobject]@{name=$Name;passed=$Passed})}
$cases=[System.Collections.Generic.List[object]]::new();$creator=Join-Path $PSScriptRoot 'new-enterprise-memory-record.ps1';$transition=Join-Path $PSScriptRoot 'set-enterprise-memory-state.ps1';$reader=Join-Path $PSScriptRoot 'read-enterprise-memory.ps1';$shareIssuer=Join-Path $PSScriptRoot 'new-enterprise-memory-share-grant.ps1';$shareRevoker=Join-Path $PSScriptRoot 'revoke-enterprise-memory-share-grant.ps1'
$common=@('-MemoryId',$memoryId,'-MemoryType','organization','-MemoryLayer','strategy','-CubeId','cube-finance','-ContentRef','policy://finance/approval-v1','-Scope','department.finance','-SourceRefs','document://policy/finance-2026-01','-Confidence','0.96','-ExpiresAt',([DateTime]::UtcNow.AddHours(1).ToString('o')),'-Visibility','authorized_only','-TenantId','tenant-memory','-OrganizationId','org-memory','-ProjectId','project-memory','-RoleId','finance-analyst','-Classification','internal_sanitized','-RecordVersion','v1','-OwnerId','owner-memory','-AuditChainRef','receipt://audit/memory','-ActorId','owner-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-ApprovalRequired','-OutputPath',$recordPath,'-PassThru')
$created=Invoke-Child $creator $common;Add-Case $cases 'candidate_record_created_without_raw_content' ($created.code-eq0-and$created.text-match'"status"\s*:\s*"candidate"'-and$created.text-match'"raw_content_stored"\s*:\s*false')
$originalHash=(Get-FileHash -LiteralPath $recordPath -Algorithm SHA256).Hash;$overwrite=Invoke-Child $creator $common;Add-Case $cases 'candidate_record_cannot_be_overwritten' ($overwrite.code-ne0-and$overwrite.text-match'memory_record_already_exists'-and(Get-FileHash -LiteralPath $recordPath -Algorithm SHA256).Hash-eq$originalHash)
$activateEarly=Invoke-Child $transition @('-MemoryPath',$recordPath,'-ToStatus','active','-ActorId','owner-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-PassThru');Add-Case $cases 'candidate_cannot_skip_verification' ($activateEarly.code-ne0-and$activateEarly.text-match'invalid_memory_state_transition')
$verified=Invoke-Child $transition @('-MemoryPath',$recordPath,'-ToStatus','verified','-ActorId','verifier-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-EvidenceRef','receipt://memory-verification','-PassThru');Add-Case $cases 'verification_requires_evidence_and_is_append_only' ($verified.code-eq0-and$verified.text-match'"effective_status"\s*:\s*"verified"'-and(Get-FileHash -LiteralPath $recordPath -Algorithm SHA256).Hash-eq$originalHash)
$noApproval=Invoke-Child $transition @('-MemoryPath',$recordPath,'-ToStatus','active','-ActorId','owner-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-PassThru');Add-Case $cases 'policy_memory_activation_requires_human_approval' ($noApproval.code-ne0-and$noApproval.text-match'human_approval_required_for_activation')
$active=Invoke-Child $transition @('-MemoryPath',$recordPath,'-ToStatus','active','-ActorId','owner-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-ApprovedBy','finance-owner','-PassThru');Add-Case $cases 'verified_memory_can_be_activated_by_owner' ($active.code-eq0-and$active.text-match'"effective_status"\s*:\s*"active"')
$grant=[ordered]@{schema_version=1;contract_type='qianlima_delegation_grant';grant_id=$grantId;tenant_id='tenant-memory';organization_id='org-memory';project_id='project-memory';role_id='finance-analyst';employee_id='employee-memory';agent_id='memory-reader';agent_version='memory-reader-v1';task_id=$taskId;trace_id=$traceId;data_refs=@((('memory://'+$memoryId)),('memory-cube://cube-finance'));allowed_tools=@('read_memory','query_memory');allowed_data_classifications=@('internal_sanitized');expires_at=[DateTime]::UtcNow.AddMinutes(10).ToString('o');status='issued'};New-Item -ItemType Directory -Path (Split-Path -Parent $grantPath) -Force|Out-Null;[IO.File]::WriteAllText($grantPath,($grant|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false))
$readArgs=@('-MemoryPath',$recordPath,'-GrantPath',$grantPath,'-TenantId','tenant-memory','-OrganizationId','org-memory','-ProjectId','project-memory','-RoleId','finance-analyst','-AgentId','memory-reader','-TaskId',$taskId,'-Purpose','Resolve approved finance workflow.','-PassThru')
$withoutShare=Invoke-Child $reader $readArgs;Add-Case $cases 'cross_agent_read_requires_explicit_share_grant' ($withoutShare.code-ne0-and$withoutShare.text-match'cross_agent_memory_share_grant_required')
$share=Invoke-Child $shareIssuer @('-MemoryPath',$recordPath,'-ShareGrantId',"share-$stamp",'-SourceAgentId','memory-governor','-TargetAgentId','memory-reader','-TaskId',$taskId,'-RoleId','finance-analyst','-ExpiresAt',([DateTime]::UtcNow.AddMinutes(10).ToString('o')),'-ApprovedBy','owner-memory','-GrantId',$grantId,'-TraceId',$traceId,'-OutputPath',$sharePath,'-PassThru');Add-Case $cases 'memory_share_is_explicit_short_lived_and_non_delegable' ($share.code-eq0-and$share.text-match'"can_delegate"\s*:\s*false'-and$share.text-match'"execution_authority"\s*:\s*false')
$read=Invoke-Child $reader (@($readArgs[0..($readArgs.Count-2)])+@('-ShareGrantPath',$sharePath,'-PassThru'));Add-Case $cases 'active_memory_read_is_cube_grant_bound_and_minimized' ($read.code-eq0-and$read.text-match'"cube_id"\s*:\s*"cube-finance"'-and$read.text-match'"full_memory_returned"\s*:\s*false'-and$read.text-match'"permission_expanded"\s*:\s*false')
$external=Invoke-Child $reader (@($readArgs[0..($readArgs.Count-2)])+@('-ShareGrantPath',$sharePath,'-ExternalAgent','-PassThru'));Add-Case $cases 'external_agent_cannot_read_long_term_memory' ($external.code-ne0-and$external.text-match'external_agent_requires_separate_sanitized_projection')
$shareRevoked=Invoke-Child $shareRevoker @('-ShareGrantPath',$sharePath,'-ActorId','owner-memory','-Reason','task_scope_ended','-GrantId',$grantId,'-TraceId',$traceId,'-PassThru');$readAfterShareRevoke=Invoke-Child $reader (@($readArgs[0..($readArgs.Count-2)])+@('-ShareGrantPath',$sharePath,'-PassThru'));Add-Case $cases 'revoked_share_grant_is_denied_before_read' ($shareRevoked.code-eq0-and$readAfterShareRevoke.code-ne0-and$readAfterShareRevoke.text-match'memory_share_grant_revoked')
$revoked=Invoke-Child $transition @('-MemoryPath',$recordPath,'-ToStatus','revoked','-ActorId','security-memory','-AgentId','memory-governor','-AgentVersion','memory-v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-EvidenceRef','receipt://memory-revocation','-PassThru');$readRevoked=Invoke-Child $reader (@($readArgs[0..($readArgs.Count-2)])+@('-ShareGrantPath',$sharePath,'-PassThru'));Add-Case $cases 'revoked_memory_is_denied_before_read' ($revoked.code-eq0-and$readRevoked.code-ne0-and$readRevoked.text-match'memory_not_active_revoked')
Add-Case $cases 'record_remains_immutable_across_lifecycle' ((Get-FileHash -LiteralPath $recordPath -Algorithm SHA256).Hash-eq$originalHash)
$failed=@($cases|Where-Object{-not$_.passed});$result=[pscustomobject]@{passed=($failed.Count-eq0);cases=@($cases);raw_content_stored=$false;external_calls=$false;listeners_opened=$false;business_write=$false};if($PassThru){$result|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise memory regression failed: '+(($failed.name)-join', '))}
