param([switch]$PassThru)
$ErrorActionPreference='Stop';$gate=Join-Path $PSScriptRoot 'invoke-identity-access-gate.ps1';$roles=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'organization-role-templates.json') -Raw -Encoding UTF8|ConvertFrom-Json;$cases=[System.Collections.Generic.List[object]]::new();function Add([string]$n,[bool]$p){$cases.Add([PSCustomObject]@{name=$n;passed=$p})};function Run([object]$r){& $gate -RequestJson ($r|ConvertTo-Json -Depth 8 -Compress) -PassThru|ConvertFrom-Json};function Copy-Object([object]$v){$v|ConvertTo-Json -Depth 8|ConvertFrom-Json}
$user=[ordered]@{user_id='u1';display_name='User';organization_id='org1';department_id='dept-ops';manager_user_id='m1';employment_type='employee';status='active';cost_center='cc1';created_at='2026-07-20T00:00:00Z'}
$assignment=[ordered]@{assignment_id='ra1';user_id='u1';organization_id='org1';role_type='business';role_id='operations_manager';scope_type='department';scope_ids=@('dept-ops');requested_by='m1';approved_by='owner1';valid_from='2026-07-20T00:00:00Z';reason='operations duty';temporary=$false}
$ok=Run ([ordered]@{user=$user;assignment=$assignment});Add 'scoped_business_role_is_eligible_without_runtime_authority' ($ok.status-eq'eligible_for_role_assignment'-and$ok.runtime_authority-eq'none'-and$ok.write_access_changed-eq$false)
$self=Copy-Object $assignment;$self.approved_by='m1';$blocked=Run ([ordered]@{user=$user;assignment=$self});Add 'self_approval_is_denied' ($blocked.status-eq'blocked'-and@($blocked.reasons)-contains'self_approval_denied')
$temp=Copy-Object $assignment;$temp.temporary=$true;$blocked=Run ([ordered]@{user=$user;assignment=$temp});Add 'temporary_role_requires_expiry' (@($blocked.reasons)-contains'temporary_expiry_required')
$priv=Copy-Object $assignment;$priv.role_type='governance';$priv.role_id='security_admin';$blocked=Run ([ordered]@{user=$user;assignment=$priv});Add 'privileged_role_requires_second_approver' (@($blocked.reasons)-contains'privileged_second_approval_required')
$suspended=Copy-Object $user;$suspended.status='suspended';$blocked=Run ([ordered]@{user=$suspended;assignment=$assignment});Add 'suspended_user_is_denied' (@($blocked.reasons)-contains'user_not_active')
Add 'business_catalog_has_requested_management_roles' (@($roles.business_roles.id)-contains'operations_manager'-and@($roles.business_roles.id)-contains'supply_chain_manager'-and@($roles.business_roles.id)-contains'finance_manager')
Add 'roles_never_grant_permanent_execution' ($roles.assignment_rules.no_role_grants_permanent_agent_execution-eq$true)
$failed=@($cases|Where-Object{-not$_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq0);cases=@($cases);external_calls=$false;changes_applied=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Identity/access regression failed: '+(($failed.name)-join', '))}
