<## .SYNOPSIS Offline regression for ETCLOVG and enterprise Task Runtime Specs. ##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$gate=Join-Path $PSScriptRoot 'invoke-enterprise-task-runtime-spec-gate.ps1';$tmp=Join-Path([IO.Path]::GetTempPath())('beijixing-runtime-spec-'+[Guid]::NewGuid().ToString('n'));New-Item -ItemType Directory -Path $tmp -Force|Out-Null;$cases=[System.Collections.Generic.List[object]]::new();$utf8=[Text.UTF8Encoding]::new($false)
function Add([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})}
function Base([string]$Risk='L2'){[ordered]@{spec_id='spec-1';spec_version='1.0.0';task_id='task-1';tenant_id='tenant-1';organization_id='org-1';project_id='project-1';human_owner_id='owner-1';goal='Verify one selected artifact.';risk_level=$Risk;capability_profile=[ordered]@{profile_id='reverse-triage';allowed_tools=@('read_metadata')};data_scope=[ordered]@{classification='internal_sanitized';source_refs=@('source:1');allowed_fields=@('metadata');expires_at='2026-07-24T00:00:00Z'};budget=[ordered]@{max_steps=5;max_tool_calls=3;max_cost=1;max_runtime_seconds=60;max_output_bytes=1024};state_machine=[ordered]@{states=@('received','planned','executing','verifying','completed','blocked','frozen','cancelled');transitions=@('received->planned','planned->executing','executing->verifying','verifying->completed');terminal_states=@('completed','blocked','frozen','cancelled')};confirmation_points=@();required_evidence=@('source_receipt','output_receipt','verification_receipt');failure_policy=[ordered]@{blocked_when=@('source_missing');freeze_when=@('scope_violation');revoke_when=@('grant_expired');recovery_action='return_to_broker'};verification=[ordered]@{producer_id='agent-1';independent_verifier_id='verifier-1';replay_ref='replay:1';acceptance_matrix_ref='etclovg-acceptance-matrix.json'};governance=[ordered]@{grant_id='grant-1';attestation_ref='attestation:1';policy_version='1.0';audit_sink_ref='audit:1'};execution=[ordered]@{authorized=$false;external_write=$false;production_write=$false};improvement=[ordered]@{mode='candidate_only';auto_apply=$false;target_files=@('workflow-candidate.json')}}}
function Run($Spec,[string]$Name){$path=Join-Path $tmp "$Name.json";[IO.File]::WriteAllText($path,($Spec|ConvertTo-Json -Depth 15),$utf8);$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate -SpecPath $path -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($out-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{code=$code;value=$value}}
try{$matrix=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'etclovg-acceptance-matrix.json')-Raw -Encoding UTF8|ConvertFrom-Json;Add 'seven_dimensions_required'(@($matrix.dimensions.PSObject.Properties).Count-eq7-and@($matrix.acceptance_rules.required_dimensions).Count-eq7)
$valid=Run(Base)'valid';Add 'valid_L2_spec_is_plan_only'($valid.code-eq0-and$valid.value.status-eq'spec_valid'-and-not$valid.value.execution_authorized)
$missing=Base;$missing.governance.grant_id='';$r=Run $missing 'missing-grant';Add 'missing_grant_blocked'($r.code-ne0-and@($r.value.reasons)-contains'missing_governance_grant_id')
$self=Base;$self.verification.independent_verifier_id='agent-1';$r=Run $self 'self';Add 'self_verification_denied'($r.code-ne0-and@($r.value.reasons)-contains'self_verification_denied')
$state=Base;$state.state_machine.transitions=@('received->planned');$r=Run $state 'state';Add 'missing_state_transition_blocked'($r.code-ne0-and@($r.value.reasons)-contains'missing_transition_planned->executing')
$l4=Base 'L4';$r=Run $l4 'l4-missing';Add 'L4_missing_controls_blocked'($r.code-ne0-and@($r.value.reasons)-contains'L4_human_approval_required')
$l4.confirmation_points=@('human_approval','preflight_snapshot','rollback_ref','post_change_verification');$r=Run $l4 'l4-valid';Add 'valid_L4_is_human_candidate'($r.code-eq0-and$r.value.status-eq'needs_human'-and$r.value.adoption_authority-eq'none')
$auto=Base;$auto.improvement.auto_apply=$true;$r=Run $auto 'auto';Add 'auto_improvement_denied'($r.code-ne0-and@($r.value.reasons)-contains'improvement_auto_apply_denied')
$target=Base;$target.improvement.target_files=@('risk-rules.yaml');$r=Run $target 'target';Add 'governance_core_target_denied'($r.code-ne0-and@($r.value.reasons)-contains'forbidden_improvement_target_risk-rules')
}finally{Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue}
$failed=@($cases|Where-Object{-not$_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq0);cases=@($cases);external_calls=$false;processes_started=$false;files_written=$false;permissions_granted=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Task runtime spec regression failed: '+($failed.name-join', '))}
