param([switch]$PassThru)
$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$stamp=(Get-Date).ToString('yyyyMMddHHmmssfff');$taskId="task-timeline-$stamp";$grantId="grant-timeline-$stamp";$traceId="trace-timeline-$stamp";$audit=Join-Path $PSScriptRoot 'append-enterprise-audit-event.ps1';$reader=Join-Path $PSScriptRoot 'get-enterprise-task-timeline.ps1';$auditPath=Join-Path $projectRoot '.qianlima\run-traces\enterprise-audit-events.jsonl'
$common=@('-TenantId','tenant-timeline','-OrganizationId','org-timeline','-UserId','employee-timeline','-AgentId','agent-timeline','-AgentVersion','v1','-TaskId',$taskId,'-GrantId',$grantId,'-TraceId',$traceId,'-PolicyVersion','enterprise-2.17.17','-OutputPath',$auditPath)
foreach($event in @(@('task_created','allow'),@('grant_issued','allow'),@('verification_completed','allow'),@('grant_revoked','revoke'),@('task_terminal','accept'))){& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $audit -EventType $event[0] -Decision $event[1] @common -EvidenceRefs "evidence:$taskId"|Out-Null;if($LASTEXITCODE-ne 0){throw "Could not write $($event[0]) fixture."}}
$raw=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $reader -TaskId $taskId -TenantId tenant-timeline -OrganizationId org-timeline -PassThru);$code=$LASTEXITCODE;$result=(($raw|ForEach-Object{$_.ToString()})-join"`n")|ConvertFrom-Json
$wrong=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $reader -TaskId $taskId -TenantId wrong-tenant -PassThru 2>&1);$wrongCode=$LASTEXITCODE
$cases=@([pscustomobject]@{name='timeline_returns_current_terminal_state';passed=($code-eq 0-and$result.status-eq'ok'-and$result.current_state-eq'accept'-and$result.grant_state-eq'revoked'-and$result.raw_content_returned-eq$false)},[pscustomobject]@{name='timeline_preserves_event_lineage';passed=($result.event_count-eq 5-and$result.events[0].task_id-eq$taskId-and$result.events[-1].event_type-eq'task_terminal'-and$result.terminal_event)},[pscustomobject]@{name='timeline_enforces_tenant_filter';passed=($wrongCode-ne 0-and(($wrong|ForEach-Object{$_.ToString()})-join"`n")-match'task_not_found')},[pscustomobject]@{name='timeline_has_no_external_calls';passed=($result.external_calls-eq$false-and$result.secret_values_returned-eq$false)})
$failed=@($cases|Where-Object{-not$_.passed});$out=[pscustomobject]@{passed=($failed.Count-eq 0);cases=$cases;external_calls=$false;listeners_opened=$false;business_write=$false};if($PassThru){$out|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise task timeline regression failed: '+(($failed.name)-join ', '))}
